apiVersion: v1
kind: Service
metadata:
  name: splunk-service
spec:
  type: LoadBalancer
  selector:
    app: splunk
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
    - protocol: TCP
      port: 8089
      targetPort: 8089
