apiVersion: apps/v1
kind: Deployment
metadata:
  name: splunk-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: splunk
  template:
    metadata:
      labels:
        app: splunk
    spec:
      containers:
        - name: splunk-container
          image: splunk/splunk:latest
          ports:
            - containerPort: 8000
            - containerPort: 8089
          env:
            - name: SPLUNK_START_ARGS
              value: --accept-license
            - name: SPLUNK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: splunk-secrets
                  key: splunk-password
